const CARD_STATUSES = {
  OK_DETAILS: 'OK_DETAILS',
  NOT_FOUND: 'NOT_FOUND',
  ERROR: 'ERROR',
  SKIP_DETAILS_PRESENT: 'SKIP_DETAILS_PRESENT',
  NEED_INPUT: 'NEED_INPUT',
  WARNING_PASSCODE_MISMATCH: 'WARNING_PASSCODE_MISMATCH'
};

const JOB_STATUSES = {
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  FAILED: 'FAILED'
};

module.exports = {
  CARD_STATUSES,
  JOB_STATUSES
};
